format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue bold"
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❱](white bold)"
error_symbol = "[❱](red bold)"
vicmd_symbol = "[❰](white bold)"

[git_branch]
format = "[$branch]($style)"
style = "bold green"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "bold green"

[time]
format = "[$time]($style) "
style = "bold fg:243"
time_format = "%H:%M:%S"
disabled = true
